theme = "monokai_pro"

[editor]
bufferline = "always"
line-number = "relative"
cursorline = true
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
# wrap-at-text-width = true
wrap-indicator = "↩ "

[editor.statusline]
left = ["mode", "spinner","spacer", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = false
characters = "╎"
skip-levels = 1

[editor.file-picker]
hidden = false

# KEY REMAPS
[keys.insert]
j = { j = "normal_mode" }

[keys.normal]
"ret" = ["move_line_down", "goto_first_nonwhitespace"]

[keys.select]
C-j = { k = "normal_mode" }
